version: "3.7"
services:
   db:
     container_name: "db_${ID}"
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     networks: 
       db:
         aliases: 
           - "db_${ID}"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     container_name: "web_${ID}"
     depends_on:
       - db
     image: wordpress
     networks: 
       front-end:
         aliases:
           - "web_${ID}"
       db:
     restart: always
     environment:
       WORDPRESS_DB_HOST: db_${ID}:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

volumes:
   db_data: {}

networks:
   db:
     external: true
   front-end:
     external: true